This Lab is about preprocessing raw Point Clouds with the use of Open3d Python library. Open3d implements several useful functions that facilitate Point Cloud processing and analysis, including downsampling, outlier removal and the estimation of normal vectors at each point. Let's jump in!

In [1]:
## import the necessary libraries
import numpy as np
import pandas as pd
import open3d as o3d
import os
import gc
from pathlib import Path

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [2]:
import matplotlib.pyplot as plt

In [3]:
maindir = Path.cwd() / "tutorial_data"
filename = "Sphere_16_75_2_0.6.txt"
path2file = maindir / filename

In [4]:
colnames = ['X', 'Y', 'Z', 'I', 'J', 'K']
ddf = pd.read_csv(path2file, names=colnames, index_col=False, sep=' ')
ddf.head()

X        Y        Z         I         J         K
0 -5.59362 -4.17652  3.82781  0.000081  0.001229  0.999999
1 -5.63422 -4.17642  3.82771  0.000081  0.001229  0.999999
2 -4.84902 -4.41662  4.55351  0.000081  0.001229  0.999999
3 -4.66562 -4.95552  4.12101  0.000081  0.001229  0.999999
4 -4.70672 -4.95542  4.12081  0.000081  0.001229  0.999999

In [5]:
## Load Point Cloud and render it
pcd = o3d.io.read_point_cloud(str(path2file), format='xyz')
print(pcd)
print(np.asarray(pcd.points))

PointCloud with 68470 points.
[[-5.59362 -4.17652  3.82781]
 [-5.63422 -4.17642  3.82771]
 [-4.84902 -4.41662  4.55351]
 ...
 [ 4.80738  5.34298  3.40841]
 [ 4.89038  5.34269  3.31971]
 [ 4.84858  5.34288  3.39041]]


In [6]:
## Load Point Cloud and render it, retrieve laser orientation as the "normals" n in "xyzn"
pcd = o3d.io.read_point_cloud(str(path2file), format='xyzn')
print(pcd)
print(np.asarray(pcd.points))

PointCloud with 68470 points.
[[-5.59362 -4.17652  3.82781]
 [-5.63422 -4.17642  3.82771]
 [-4.84902 -4.41662  4.55351]
 ...
 [ 4.80738  5.34298  3.40841]
 [ 4.89038  5.34269  3.31971]
 [ 4.84858  5.34288  3.39041]]


In [7]:
np.asarray(pcd.normals)

array([[8.14835e-05, 1.22949e-03, 9.99999e-01],
       [8.14835e-05, 1.22949e-03, 9.99999e-01],
       [8.14835e-05, 1.22949e-03, 9.99999e-01],
       ...,
       [8.14835e-05, 1.22949e-03, 9.99999e-01],
       [8.14835e-05, 1.22949e-03, 9.99999e-01],
       [8.14835e-05, 1.22949e-03, 9.99999e-01]])

In [8]:
## retrieve laser orientation as the "normals" n in "xyzn"
laser_ori = np.asarray(pcd.normals)
print(laser_ori)

[[8.14835e-05 1.22949e-03 9.99999e-01]
 [8.14835e-05 1.22949e-03 9.99999e-01]
 [8.14835e-05 1.22949e-03 9.99999e-01]
 ...
 [8.14835e-05 1.22949e-03 9.99999e-01]
 [8.14835e-05 1.22949e-03 9.99999e-01]
 [8.14835e-05 1.22949e-03 9.99999e-01]]


In [9]:
## Visualize the Point Cloud
o3d.visualization.draw_geometries([pcd],
                                 window_name='Sphere 16mm Raw Point Cloud',
                                 width=1920,
                                 height=1080)

In [10]:
## Downsampling with voxelization
print("Downsample the point cloud with a voxel of 0.05")
downpcd=pcd.voxel_down_sample(voxel_size=0.05)
o3d.visualization.draw_geometries([downpcd],
                                 window_name='Downsampled sphere, voxel=0.05',
                                 width=1920,
                                 height=1080)

Downsample the point cloud with a voxel of 0.05


In [11]:
## Downsampling with voxelization, larger voxel
print("Downsample the point cloud with a voxel of 0.08")
downpcd=pcd.voxel_down_sample(voxel_size=0.08)
o3d.visualization.draw_geometries([downpcd],
                                 window_name='Downsampled sphere, voxel=0.08',
                                 width=1920,
                                 height=1080)

Downsample the point cloud with a voxel of 0.08


In [12]:
## Uniform downsampling, every k points
print("Every 5th points are selected")
uni_down_pcd=pcd.uniform_down_sample(every_k_points=5)
o3d.visualization.draw_geometries([uni_down_pcd],
                                 window_name='Uniformly downsampled Sphere, Every 5th points are selected',
                                 width=1920,
                                 height=1080)

Every 5th points are selected


In [13]:
# ## Radius outlier removal: Removes points that have neighbors less than nb_points in a sphere of a given radius
# print("Radius outlier removal")
# cloud,ind=pcd.remove_radius_outlier(nb_points=20,radius=0.6)
# inlier_cloud=cloud.select_by_index(ind)
# outlier_cloud=cloud.select_by_index(ind,invert=True)
# print("Showing outliers(red) and inliers(gray):")
# outlier_cloud.paint_uniform_color([1,0,0])
# inlier_cloud.paint_uniform_color([0.8,0.8,0.8])
# o3d.visualization.draw_geometries([inlier_cloud,outlier_cloud],
#                                   window_name='Uniformly downsampled Sphere, Every 5th points are selected',
#                                   width=1920,
#                                   height=1080,
#                              zoom=0.3210,
#                              front=[0.4, 0.4, 0.7],
#                              lookat=[0, 0,-0.8795],
#                              up=[0.01, 0.01, 0.2024])

In [ ]:
## Radius outlier removal: Removes points that have neighbors less than nb_points in a sphere of a given radius
print("Radius outlier removal")
cloud,ind=pcd.remove_radius_outlier(nb_points=20,radius=0.5)
inlier_cloud=cloud.select_by_index(ind)
outlier_cloud=cloud.select_by_index(ind,invert=True)
print("Showing outliers(red) and inliers(gray):")
outlier_cloud.paint_uniform_color([1,0,0])
inlier_cloud.paint_uniform_color([0.8,0.8,0.8])
o3d.visualization.draw_geometries([inlier_cloud,outlier_cloud],
                                  window_name='Radius outlier removal, Showing outliers(red) and inliers(gray)',
                                  width=1920,
                                  height=1080)

In [1]:
## Statistical outlier removal: Removes points that are further away from their neighbors in average
print("Statistical outlier removal")
cloud,ind=pcd.remove_statistical_outlier(nb_neighbors=60,std_ratio=1.0)
inlier_cloud=pcd.select_by_index(ind)
outlier_cloud=pcd.select_by_index(ind,invert=True)
print("Showing outliers(red) and inliers(gray):")
outlier_cloud.paint_uniform_color([1,0,0])
inlier_cloud.paint_uniform_color([0.8,0.8,0.8])
o3d.visualization.draw_geometries([inlier_cloud,outlier_cloud],
                                  window_name='Statistical outlier removal, Showing outliers(red) and inliers(gray)',
                                  width=1920,
                                  height=1080)

Statistical outlier removal


NameError: name 'pcd' is not defined

In [ ]:
## Compare raw to filtered Point Cloud size
print(pcd)
print(inlier_cloud)

In [ ]:
## Random downsampling, Sampling ratio: the ratio of number of selected points to total number of points[0-1]
print("Random downsampling")
random_down_pcd=inlier_cloud.random_down_sample(sampling_ratio = 0.2)
random_down_pcd.paint_uniform_color([0, 1, 0])
o3d.visualization.draw_geometries([random_down_pcd],
                                 window_name='Randomly downsampled Sphere with sampling ratio = 0.2',
                                 width=1920,
                                 height=1080)

In [ ]:
## Compare filtered to downsampled Point Cloud size
print(inlier_cloud)
print(random_down_pcd)

In [ ]:
## Recompute the normals of the raw Point Cloud
inlier_cloud.estimate_normals(search_param=o3d.geometry.KDTreeSearchParamHybrid(radius=0.6,max_nn=20 ))
frame = o3d.geometry.TriangleMesh.create_coordinate_frame(size=1.0, origin=random_down_pcd.get_center())
o3d.visualization.draw_geometries([inlier_cloud, frame],
                                 window_name='Recompute the normals of the filtered & downsampled point cloud',
                                 width=1920,
                                 height=1080,
                                 point_show_normal=True)

In [ ]:
## Ensure normal vectors are consistently aligned
inlier_cloud.orient_normals_consistent_tangent_plane(100)
o3d.visualization.draw_geometries([inlier_cloud, frame],
                                 window_name='Recompute the normals of the filtered & downsampled point cloud',
                                 width=1920,
                                 height=1080,
                                 point_show_normal=True)

In [ ]:
## Recompute the normals of the downsampled Point Cloud
random_down_pcd.estimate_normals(search_param=o3d.geometry.KDTreeSearchParamHybrid(radius=0.8,max_nn=100 ))
## Ensure normal vectors are consistently aligned
random_down_pcd.orient_normals_consistent_tangent_plane(100)
frame = o3d.geometry.TriangleMesh.create_coordinate_frame(size=1.0, origin=[0, 0, 0])
o3d.visualization.draw_geometries([random_down_pcd, frame],
                                 window_name='Recompute the normals of the filtered & downsampled point cloud',
                                 width=1920,
                                 height=1080,
                                 point_show_normal=True)

In [ ]:
## Retrieve number of points in the final Point Cloud & Create data array for processed Point Cloud
point_num = len(random_down_pcd.points)
points_normals_laser = np.concatenate((
                        np.asarray(random_down_pcd.points), np.asarray(random_down_pcd.normals), laser_ori[:point_num]), axis=1)
print(points_normals_laser.shape)

In [ ]:
## Create Dataframe for processed Point Cloud
colnames = ['X', 'Y', 'Z', 'Nx', 'Ny', 'Nz', 'I', 'J', 'K']
df = pd.DataFrame(points_normals_laser, columns=colnames)
df

In [ ]:
## Use laser orientation & the computed normal vectors for feature extraction: 
## Calculate the Incidence angle of light on the surface at each point
def cosine_incidence(i1, j1, k1, i2, j2, k2):
    n1 = np.sqrt(i1**2 + j1**2 + k1**2)
    n2 = np.sqrt(i2**2 + j2**2 + k2**2)
    dot = np.dot([i1, j1, k1], [i2, j2, k2])
    cos = dot / (n1*n2)
    return np.arccos(cos)

nvec_cos = np.vectorize(cosine_incidence)

In [ ]:
## Use laser orientation & the computed normal vectors for feature extraction: 
## Calculate the Incidence angle of light on the surface at each point (in radians)
df['IncAngle'] = nvec_cos(df.Nx, df.Ny, df.Nz, df.I, df.J, df.K)
df

In [ ]:
## Retrieve geometry, diameter & scanning parameters from filename
sparams = filename[:-4].split('_')
geometry = sparams[0]
diameter = float(sparams[1])
lateral_density = int(sparams[2])
direction_density = int(sparams[3])
exposure_time = float(sparams[4])
print('Geometry: ', geometry)
print('Diameter: ', diameter, ' mm')
print('Lateral Density: ', lateral_density)
print('Direction Density: ', direction_density)
print('Exposure Time: ', exposure_time)

In [ ]:
## Insert scanning parameters & nominal radius in data array
df['LateralDensity'] = lateral_density
df['DirectionDensity'] = direction_density
df['ExposureTime'] = exposure_time
df['Rnom'] = diameter/2
df

In [ ]:
## Calculate radial point deviations from nominal surface: this is the target variable
def calculate_radial_point_dev(x, y, z, radius):
    r = np.sqrt(x**2 + y**2 + z**2)
    return float(r - radius)

nvec_dev = np.vectorize(calculate_radial_point_dev)

df['PointDev'] = nvec_dev(df.X, df.Y, df.Z, df.Rnom)
df

In [ ]:
## Save processed Point Cloud in .csv tabular format: data injestible by ML models!
savefile = filename[:-4]
savefile += ".csv"
savepath = maindir / savefile
df.to_csv(savepath, sep=',', header=True, index=False)

In [ ]:
del df
gc.collect()